#!/usr/bin/env bash

set -euo pipefail

source ${CLENV_ROOT}/lib/util.shrc
source ${CLENV_ROOT}/lib/clamdb.shrc

if [[ ${CLAM_DEBUG:-} ]]; then
  set -x
fi

git_sync() {
  local _src=$1
  local _dest=$2

  if [ -d $_dest ]; then
    cd $_dest
    git pull
  else
    git clone --depth=1 ${_src} ${_dest}
    cd $_dest
  fi
}

parse_arg() {
  local arg=$1
  local ifs=$IFS
  IFS=","
  set -- $arg
  tgt_name=$1
  tgt_src=${2:-$1}
  if [[ $tgt_name = $tgt_src ]]; then
    tgt_name=""
  fi
}

parse_arg $1

if [[ $tgt_src = "-r" || $tgt_src = "--require" ]]; then
  exec ${CLENV_ROOT}/libexec/clam-install-deps ${2:-}
fi

clamdb.init

check_installed() {
  local _name=$1
  local _post_process=${2:-}
  local _installed=$(clamdb.find $_name | tr '\t' ' ')
  if [[ $_installed ]]; then
    echo "$_installed already installed. Quit." >&2
    if [[ $_post_process ]]; then
      $_post_process
    fi
    exit 1
  fi
}

if [[ $tgt_name ]]; then
  check_installed $tgt_name
fi

mode=""
module=""

if [ -d $tgt_src ]; then
  _path=$(cd $tgt_src; pwd)
  module=${_path##*/}
  if [ -r ${tgt_src}/clam.spec ]; then
    mode=copy
  else
    echo "clam.spec file not found! Can't install." >&2
    exit 1
  fi
else
  case "$tgt_src" in
    *:* )
      mode=git
      ;;
    * )
      ;;
  esac
fi

if [[ -z $mode ]]; then
  echo "Don't know how to install $tgt_src" >&2
  exit 1
fi
if [[ -z $module ]]; then
  module=${tgt_src##*/}
  module=${module%.git}
fi

workdir=${CLENV_ROOT}/tmp/${module}

echo "Sync ${tgt_src} into working directory"
case "$mode" in
  "copy" )
    cp -rp $tgt_src $workdir
    ;;
  "git" )
    git_sync $tgt_src $workdir
    ;;
  * )
    ;;
esac

cleanup() {
  rm -rf $workdir
}

cd $workdir

if [ -r clam.spec ];then
  unset name
  unset version
  unset executables
  unset resources
  source clam.spec
  name=${name:-$module}
  version=${version:-noversion}
else
  echo "clam.spec file not found! Can't install." >&2
  cleanup
  exit 1
fi

dest_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/modules
dest_module=${dest_dir}/${name}

check_installed $name cleanup

cp -rp $workdir $dest_module
echo "Sync ${module} into ${dest_module}"
cd $dest_module
cleanup

bin_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/bin
lib_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/lib

install_materials() {
  local _src=$1
  local _dest=$2
  local f __path

  if [[ $_src ]]; then
    for f in $(\ls -1 $_src); do
      if [ -f $f ]; then
        __path=$(abspath $f)
        ln -s ${__path} ${_dest}/
      else
        echo "Not exist $f Skip." >&2
      fi
    done
  fi
}

install_materials "${executables:-}" $bin_dir
install_materials "${resources:-}" $lib_dir

clamdb.add $name $version

echo "Installed ${name} ${version}"

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clam-install> - Install C<clam> modules

=head1 SYNOPSYS

Install or Update:

    clam-install git://<repos-url>
    clam-install /path/to/module
    # With module name
    clam-install foo,git://<repos-url>

    # Install from Clamfile
    clam-install -r|--require [Clamfile]

=head1 DESCRIPTION

This script installs C<clam> modules.

=head1 AUTHORS

YASUTAKE Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 YASUTAKE Kiyoshi

=cut

__EOF__

