#!/usr/bin/env bash

set -euo pipefail
[[ ${CLAM_DEBUG:-} ]] && set -x

source ${CLENV_ROOT}/lib/util.bashrc
source ${CLENV_ROOT}/lib/version.bashrc
source ${CLENV_ROOT}/lib/clamdb.bashrc

SHIMS_DIR=${CLENV_ROOT}/shims
SHIM_TEMPLATE=${CLENV_ROOT}/resource/shim-template

git_sync() {
  local _src=$1
  local _dest=$2

  if [ -d $_dest ]; then
    cd $_dest
    git pull
  else
    git clone --depth=1 ${_src} ${_dest}
    cd $_dest
  fi
}

if [[ $1 = "-r" || $1 = "--require" ]]; then
  exec ${CLENV_ROOT}/libexec/clam-install-deps ${2:-}
fi

parse_arg() {
  local arg=$1
  local ifs=$IFS
  IFS=","
  set -- $arg
  tgt_name=$1
  tgt_src=${2:-$1}
  tgt_ver=${3:-0}
  if [[ $tgt_name = $tgt_src ]]; then
    tgt_name=""
  fi
  IFS=$ifs
}

parse_arg $1

clamdb_init

force_install=""
if [[ ${2:-} = "-f" || ${2:-} = "--force" ]]; then
  force_install="true"
fi

check_installed() {
  local _name=$1
  local _version=$2
  local _post_process=${3:-}
  installed=$(clamdb_find $_name | tr '\t' ' ')
  local _ary i_name i_ver
  if [[ $installed ]]; then
    _ary=($(echo $installed))
    i_name=${_ary[0]}
    i_ver=${_ary[1]}
    version_compare $i_ver $_version comp_ret
    if (( $comp_ret >= 0 )); then
      echo "$installed already installed. Quit." >&2
      if [[ $_post_process ]]; then
        $_post_process
      fi
      exit 1
    fi
    unset comp_ret
  fi
}

if [[ $tgt_name && -z $force_install ]]; then
  check_installed $tgt_name $tgt_ver
fi

mode=""
module=$tgt_name

if [ -d $tgt_src ]; then
  _path=$(cd $tgt_src; pwd)
  if [ -r ${tgt_src}/clam.spec ]; then
    mode=copy
  else
    echo "clam.spec file not found! Can't install." >&2
    exit 1
  fi
  if [[ -z $module ]]; then
    module=${_path##*/}
  fi
else
  case "$tgt_src" in
    *:* )
      mode=git
      ;;
    * )
      ;;
  esac
fi

if [[ -z $mode ]]; then
  echo "Don't know how to install $tgt_src" >&2
  exit 1
fi
if [[ -z $module ]]; then
  module=${tgt_src##*/}
  module=${module%.git}
fi

workdir=${CLENV_ROOT}/tmp/${module}

echo "Sync ${tgt_src} into working directory"
case "$mode" in
  "copy" )
    cp -rp $tgt_src $workdir
    ;;
  "git" )
    git_sync $tgt_src $workdir
    ;;
  * )
    ;;
esac

cleanup() {
  rm -rf $workdir
}

cd $workdir

if [ -r clam.spec ];then
  unset name
  unset version
  unset executablepath
  unset executables
  unset librarypath
  unset libraries
  source clam.spec
  name=${name:-$module}
  version=${version:-0}
  if [[ "${executablepath:-}" && "${executables:-}" ]]; then
    echo "Can't specify both 'executablepath' and 'executables' at once!" >&2
    exit 1
  fi
  if [[ "${librarypath:-}" && "${libraries:-}" ]]; then
    echo "Can't specify both 'librarypath' and 'libraries' at once!" >&2
    exit 1
  fi
else
  echo "clam.spec file not found! Can't install." >&2
  cleanup
  exit 1
fi

dest_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/modules
dest_module=${dest_dir}/${name}

if [[ $force_install ]]; then
  installed=$(clamdb_find $name | tr '\t' ' ')
  if [[ $installed ]]; then
    echo "$installed installed. Force re-install."
    ${CLENV_ROOT}/libexec/clam-uninstall $name
  fi
else
  check_installed $name $version cleanup
  if [[ $installed ]]; then
    echo "$installed installed. Update to $version."
    ${CLENV_ROOT}/libexec/clam-uninstall $name
  fi
fi

cp -rp $workdir $dest_module
echo "Sync ${module} into ${dest_module}"
cd $dest_module
cleanup

bin_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/bin
lib_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/lib

check_materials() {
  local _srcs="$1"
  [[ "$_srcs" ]] || return 0
  local _dest=$2
  local _type=${3:-}
  local err f _b __dest_path

  for f in $_srcs; do
    if [[ $_type = "--executable" ]]; then
      if [[ ! -x $f ]]; then
        err=1
        echo "[Error] Not executable $f." >&2
        continue
      fi
    elif [[ ! -e $f ]]; then
      err=1
      echo "[Error] Not exit $f." >&2
      continue
    fi

    _b=${f##*/}
    __dest_path=${_dest}/${_b}
    if [[ -e ${__dest_path} ]]; then
      err=1
      echo "[Error] Some file already exists at install path! ${__dest_path}" >&2
      continue
    fi
  done

  [[ -z "${err:-}" ]] || exit 1
}

install_materials() {
  local _srcs="$1"
  [[ "$_srcs" ]] || return 0
  local _dest=$2
  local _shim=${3:-}
  local f _b __src_path __dest_path

  for x in $_srcs; do
    _b=${x##*/}
    __dest_path=${_dest}/${_b}
    __src_path=$(abspath $x)
    ln -s ${__src_path} ${__dest_path}
    [[ -z "$_shim" ]] || create_shim "${_b}"
  done
}

create_shim() {
  local _cmd="$1"
  local _shim="${SHIMS_DIR}/${_cmd}"
  [[ -x ${_shim} ]] && return

  install ${SHIM_TEMPLATE} $_shim
  echo "${_shim} created."
  return 0
}

if [[ "${executablepath:-}" ]]; then
  executables="$(echo $(find $executablepath -mindepth 1 -maxdepth 1))"
fi
if [[ "${librarypath:-}" ]]; then
  libraries="$(echo $(find $librarypath -mindepth 1 -maxdepth 1))"
fi

check_materials "${executables:-}" $bin_dir --executable
check_materials "${libraries:-}" $lib_dir

install_materials "${executables:-}" $bin_dir --shims
install_materials "${libraries:-}" $lib_dir

clamdb_add $name $version

echo "Installed ${name} - ver ${version}"

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clam-install> - Install C<clam> modules

=head1 SYNOPSYS

Install or Update:

    clam-install git://<repos-url> [OPTION]
    clam-install /path/to/module [OPTION]
    # With module name
    clam-install foo,git://<repos-url>
    # With module name and version
    clam-install foo,git://<repos-url>,1.1

    # Force install
    clam-install git://<repos-url> -f|--force

    # Install from Clamfile
    clam-install -r|--require [Clamfile]

=head1 DESCRIPTION

This script installs C<clam> modules.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

