#!/usr/bin/env bash

set -euo pipefail
[[ ${CLENV_DEBUG:-} ]] && set -x

source ${CLENV_ROOT}/shrc.d/clenv.shrc

for env in $(\ls -1 ${CLENV_ROOT}/environments/); do
  prefix=" "
  if [[ $env = $CLENV_ENVIRONMENT ]]; then
    prefix="*"
  fi
  echo "${prefix} ${env}"
done

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clenv-environs> - List C<clenv> environments

=head1 SYNOPSYS

    clenv environs

=head1 DESCRIPTION

This command shows all C<clenv> environments in the system.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

