#!/usr/bin/env bash

set -euo pipefail
[[ ${CLENV_DEBUG:-} ]] && set -x

CLENV_COMMAND="$1"

if [[ -z "${CLENV_COMMAND}" ]]; then
  pod2text $0 >&2
  exit 1
fi

CLENV_COMMAND_PATH="$(clenv-which "${CLENV_COMMAND}")"
CLENV_COMMAND_DIR="${CLENV_COMMAND_PATH%/*}"

shift
export PATH="${CLENV_COMMAND_DIR}:$PATH"

exec -a "${CLENV_COMMAND}" "${CLENV_COMMAND_PATH}" "$@"

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clenv-exec> - Execute command in clenv

=head1 SYNOPSYS

    clenv-exec COMMAND

=head1 DESCRIPTION

This command executes target command in C<clenv> environment.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

