#!/usr/bin/env bash

set -euo pipefail
[[ ${CLENV_DEBUG:-} ]] && set -x

source ${CLENV_ROOT}/shrc.d/clenv.shrc

if [[ -z "${CLENV_ENVIRONMENT:-}" ]]; then
  echo '$CLENV_ENVIRONMENT is not set' >&2
  exit 1
elif [[ ! -d ${__clenv_base_dir}/environments/$CLENV_ENVIRONMENT ]]; then
  echo "Environment '${CLENV_ENVIRONMENT}' is not created" >&2
  exit 1
fi

echo $CLENV_ENVIRONMENT

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clenv-environ> - Show current C<clenv> environment

=head1 SYNOPSYS

    clenv environ

=head1 DESCRIPTION

This command shows current C<clenv> environment.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

