#!/usr/bin/env bash

set -euo pipefail
[[ ${CLENV_DEBUG:-} ]] && set -x

env=${1:-default}
env_dir=${CLENV_ROOT}/environments/$env
if [[ -d $env_dir ]]; then
  echo "'$env' already exists" >&2
else
  mkdir -p ${env_dir}/{bin,lib,modules}
  echo "Initialized env '$env'"
fi

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clenv-create> - Create a C<clenv> environment

=head1 SYNOPSYS

    clenv create [$env]

=head1 DESCRIPTION

This command initialize a C<clenv> environment with specified name.

If no argument is given, it creates "default" environment.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

