#!/usr/bin/env bash

set -euo pipefail
[[ ${CLENV_DEBUG:-} ]] && set -x

source ${CLENV_ROOT}/lib/clenv_environment.bashrc

if [[ -z "${CLENV_ENVIRONMENT:-}" ]]; then
  CLENV_ENVIRONMENT_FILE="$(clenv_environ_file)"
  CLENV_ENVIRONMENT="$(clenv_environ "${CLENV_ENVIRONMENT_FILE}" || true)"
fi

if [[ -z "${CLENV_ENVIRONMENT:-}" ]]; then
  echo '$CLENV_ENVIRONMENT is not set' >&2
  exit 1
fi

if [[ ! -d "${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}" ]]; then
  echo "Environment '${CLENV_ENVIRONMENT}' is not created" >&2
  exit 1
fi

if [[ -n "${CLENV_ENVIRONMENT_FILE:-}" ]]; then
  echo "$CLENV_ENVIRONMENT (set by ${CLENV_ENVIRONMENT_FILE})"
else
  echo "$CLENV_ENVIRONMENT (set by CLENV_ENVIRONMENT)"
fi

exit 0

: <<'__EOF__'

=encoding utf8

=head1 NAME

B<clenv-environ> - Show current C<clenv> environment

=head1 SYNOPSYS

    clenv environ

=head1 DESCRIPTION

This command shows current C<clenv> environment.

=head1 AUTHORS

IKEDA Kiyoshi E<lt>yasutake.kiyoshi@gmail.comE<gt>

=head1 LICENSE

The MIT License (MIT)

Copyright (c) 2016 IKEDA Kiyoshi

=cut

__EOF__

